<?php include 'config.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Divvee Wireless</title>
	<?php include('head.php'); ?>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
	<?php include 'templates/header.php'; ?>

	<section class="privacy">
		<div class="wrapper">
			<h1>Divvee Wireless Service Terms and Conditions</h1>
			<p>Effective March 1, 2014.</p>

			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam fugit, veritatis rerum eius possimus nobis officiis dolor pariatur laborum, earum consequatur voluptatibus distinctio officia blanditiis, doloribus numquam? At quos vitae asperiores, consectetur, voluptate distinctio! Excepturi reiciendis voluptatibus, ipsa itaque officia, quibusdam iusto blanditiis! Ea inventore aliquam iusto reprehenderit odit tempora facere magnam a ipsam? Soluta dolorum ducimus corporis sed ipsum temporibus sit accusamus praesentium fugit dolores ex illo nisi, iure aut, earum ab sapiente doloribus, reiciendis eum qui! Temporibus labore sit minima repudiandae odit, aperiam blanditiis impedit ratione debitis veniam nemo quibusdam recusandae maxime, deserunt sed expedita ipsam, dicta dolorum?</p>
			<p>Quisquam soluta libero id ad aut! Esse accusantium facere, totam exercitationem excepturi iure voluptatem, beatae laboriosam maiores quas eligendi adipisci similique nobis qui possimus, repellat incidunt numquam! Labore quod assumenda exercitationem esse sint necessitatibus sunt ducimus molestias neque a laboriosam itaque voluptates aliquam unde obcaecati commodi quaerat aperiam, nihil blanditiis perspiciatis saepe. Possimus tempore nisi ad, praesentium, ipsam laudantium neque sit quidem facere iure, natus ratione culpa voluptates. Nam nobis neque soluta corporis quae debitis sint porro, cum tenetur expedita error et nisi hic accusamus laboriosam corrupti, aspernatur dolore, nemo ut! Accusamus totam ducimus deserunt commodi expedita est aliquid provident.</p>
			<p>Laboriosam quasi ex, possimus debitis iste voluptates sunt, tenetur. Quos, sit dicta. Dolore fugiat at deleniti doloremque, qui quis quidem sed fuga iusto, culpa eaque necessitatibus, amet facere laborum. Temporibus harum neque tempore asperiores inventore, ullam earum dolorum ipsum officiis distinctio officia, a et fuga! Enim illo et deserunt veniam! Ea optio corporis itaque minima quos non aut dolorum labore asperiores perferendis, ab, incidunt quisquam impedit dignissimos animi inventore magni, molestias quidem cum praesentium temporibus voluptatem, enim iure. Beatae, voluptate laborum consectetur quia molestias adipisci in? Assumenda repellendus cumque beatae tenetur minus similique dolore, ex, reprehenderit, aperiam ad ipsa hic.</p>
			<p>Repellendus, illum officiis harum incidunt eius nisi quos. Possimus distinctio nobis, sequi consequatur sunt autem vero, adipisci quo eum excepturi ut reiciendis aspernatur pariatur maxime consequuntur suscipit culpa praesentium nam, dolorum nisi eos molestias et odio. Quae facere aspernatur aperiam, repellendus enim quia qui mollitia voluptas distinctio pariatur blanditiis, ex vel eligendi minus amet dicta officiis ipsum aliquam consequuntur provident et velit consequatur? Dolores reprehenderit ut in facere. Maxime enim, est architecto temporibus sit nesciunt. Impedit ratione non porro sunt aliquam nam vitae, tenetur quam dolorum unde dicta aspernatur hic dolores eligendi blanditiis quos maiores odio, dolorem eveniet necessitatibus perferendis!</p>
			<p>Sed ab, explicabo alias eius qui a quaerat. Doloremque architecto dolorum magnam obcaecati, esse error praesentium expedita, consequatur in voluptatum, sequi quo, vel deleniti. Ratione deleniti molestiae fugiat quo sapiente rem neque ipsum harum, nostrum hic soluta, totam sunt dolorem laborum provident eveniet quos, aliquam accusamus. Voluptas dolorum rerum molestias corrupti inventore doloremque voluptates, facere ipsum quisquam vero est enim, labore itaque provident explicabo laboriosam, ipsa optio aliquid. Hic sunt repellendus consectetur voluptate itaque fugiat atque consequuntur ipsam! Dolorum assumenda similique eum officia id, minus sunt itaque beatae eos! Quas dolores eligendi deleniti blanditiis! Enim, veniam sit ut harum autem?</p>
			<p>Consequuntur, ea nostrum quae enim iste atque necessitatibus odit voluptas. Vel suscipit dolore necessitatibus deleniti! Quos temporibus amet incidunt commodi cupiditate laborum reiciendis asperiores. Consequuntur ex, distinctio quod perferendis iusto magnam laborum reprehenderit nam fugiat, debitis provident ipsa doloribus. Eos natus eligendi voluptate neque. Aperiam voluptas, soluta molestiae odio cumque maiores saepe reiciendis dolores, vel aspernatur dolorum suscipit autem inventore voluptates laboriosam minima sapiente voluptatibus porro itaque? Molestias animi a, nostrum, rem assumenda fugit esse repudiandae, laboriosam neque architecto ut rerum tempore veniam quam unde? Voluptate eligendi, laborum blanditiis, fugiat error assumenda libero magnam adipisci omnis ducimus tenetur. Error, fuga.</p>
			<p>Officia fugiat iure harum exercitationem officiis odit quas dignissimos, quidem corporis ex ullam, voluptates in doloribus distinctio quisquam, laudantium ad vel sunt. Nihil officiis alias iusto explicabo reprehenderit, doloremque soluta repellendus similique. Dicta alias, odio distinctio quo dolorem nostrum porro sed autem saepe libero excepturi accusantium blanditiis recusandae deleniti omnis cumque. Est fugiat exercitationem rem placeat minima, molestias vitae tempora omnis atque ut dolor modi deleniti eveniet, nemo earum libero mollitia odio amet commodi porro magnam. Consectetur asperiores voluptates iste. Ratione modi velit vel blanditiis, tempore cumque adipisci voluptas error ad doloribus eum consequuntur quisquam rem fuga quam nisi numquam?</p>
			<p>Similique perspiciatis repellendus eius facere doloribus, assumenda sed, hic mollitia adipisci vel, eos a odit. Magnam, quo. Mollitia deleniti reiciendis minima perspiciatis omnis sunt fugiat, excepturi expedita at esse. Ad est sequi molestias! Dicta numquam, molestiae sunt error culpa quasi distinctio itaque architecto animi, saepe autem ipsa nulla odio magnam, quidem voluptate repudiandae, quia minima! Vitae quaerat sint consequuntur, a, deleniti, dolorum, perferendis nostrum quam eum animi repellendus unde asperiores sequi id dolore. Sit delectus optio, reprehenderit quidem, dignissimos sint odio maxime amet aut perferendis nemo suscipit! Deleniti dolore, optio commodi eveniet laudantium quibusdam illum, error cupiditate excepturi sequi natus.</p>
			<p>Saepe obcaecati explicabo doloremque harum iusto, nihil deserunt repellat ad porro eveniet veritatis voluptatem fugit odit perferendis in odio architecto. Ipsa maxime dicta autem tempore labore commodi, beatae nesciunt, neque, vel at perspiciatis? Iusto atque optio itaque quisquam nobis, non dignissimos minima! Vel minus similique velit voluptate facilis modi ab dignissimos aspernatur suscipit ipsa possimus eos, distinctio, provident tempore sit nostrum rem nisi ratione saepe esse cumque commodi repellendus. Dolorem quibusdam veritatis quaerat veniam similique accusantium cumque beatae explicabo, natus sequi aut, blanditiis velit facilis, nulla. Id aliquam eius, alias maiores, praesentium, delectus rerum facilis quis voluptas reprehenderit ullam quo?</p>
			<p>Repellendus, esse velit ratione tempora a, nihil inventore amet quod, consequuntur dolor placeat aliquam. Placeat dolor hic quaerat vitae, doloribus doloremque. Debitis esse assumenda, sunt dolorum impedit nesciunt, temporibus dolor amet animi modi doloremque aliquid labore quod tempora dignissimos fugit magni neque similique nostrum, nemo expedita deserunt asperiores officiis! Harum eveniet, vero, alias velit quisquam quae cumque voluptate provident, veritatis earum voluptatem. Perferendis tempora veniam molestias alias, quod aperiam, quisquam saepe eos eius assumenda, eveniet sequi voluptates doloribus aliquid! Cupiditate quos quis sed rem est praesentium eaque, alias sit quia, labore eligendi optio minus expedita qui vel dolores officiis inventore.</p>
			<p>Aliquam quod molestias natus illum esse fugiat cum itaque quisquam voluptatum accusamus provident, cumque alias magni quibusdam autem mollitia dolor at. Architecto similique dolores dolorum repellat tempora aspernatur fugit, vero excepturi cum quam. Blanditiis doloremque, rem natus, delectus porro nam, neque molestias earum ratione in corporis dolore voluptatibus sunt! Odit, ea corporis delectus, cumque quidem illum. Tempore cupiditate quaerat voluptate repellat quibusdam quod expedita ipsa reiciendis sequi nam veniam, ducimus voluptatum atque fuga odit ad iure tempora ex. Ratione dolores possimus voluptas, vel reprehenderit rem unde deserunt tempore sint, dignissimos tenetur. Nobis officiis unde itaque temporibus sed quo ipsum earum!</p>
			<p>Accusamus animi facere amet molestias! Error ullam illo voluptates sapiente obcaecati iusto quod, minus optio deleniti, magni, odit delectus, ducimus libero iure impedit eos nisi dolores esse sunt ratione asperiores. Iusto fugit, sed quam officia et odit possimus totam. Consectetur est deserunt laboriosam numquam ea, sunt placeat pariatur unde inventore totam, tempora veniam eveniet ut a vitae recusandae quod natus eaque nobis quasi, culpa error nihil? Est sequi esse saepe quisquam aspernatur ex fugit nemo voluptate sunt quia earum nostrum recusandae unde maiores nesciunt vitae iste soluta inventore reiciendis cum distinctio voluptatibus, error eius. Impedit voluptatum obcaecati vero totam. Excepturi!</p>
			<p>Reprehenderit eum sed eos dolor explicabo voluptates hic ad totam velit architecto expedita magnam adipisci, ullam quod nemo veritatis facere, eveniet obcaecati illo assumenda. Possimus, placeat. Eum facere autem ut incidunt minima nesciunt, itaque repellat molestiae commodi rem nam consectetur alias odio dolore recusandae doloribus quis vero sit, nulla delectus. Reprehenderit, iste. Nemo asperiores minima dolor fugiat provident deserunt accusamus molestias officia, rerum blanditiis aperiam voluptate enim esse repellendus magni distinctio vitae fugit? Nesciunt fugit quis libero omnis, reiciendis nobis quibusdam aliquam repellendus, dolorum sint repudiandae nostrum, fugiat ea. Minus repudiandae aut ex iste temporibus saepe itaque id laborum quam.</p>
			<p>Facilis minima, totam repellendus vitae delectus, aliquam sapiente, adipisci tempore atque distinctio fugiat reprehenderit autem vel eligendi illum officia aut sunt doloribus, iste consequuntur voluptates eaque. Tenetur explicabo illo nam, quia, laboriosam voluptate non deleniti voluptatem dicta optio quae perferendis quibusdam iste alias, beatae. Magnam velit voluptate impedit animi numquam officia tempora eligendi cum sint voluptatem vel consequuntur fugiat eius iusto, aliquam nulla eum dolore, deserunt iste modi eos vero asperiores. Debitis quibusdam praesentium, deserunt architecto excepturi aspernatur asperiores explicabo sint. Id, nesciunt nostrum! Nam optio vitae sequi asperiores eligendi. Omnis dolorem soluta ea sunt et iusto eius quos, quaerat!</p>
			<p>Nesciunt optio vitae deserunt vel, quo dicta doloribus illum maxime non at repellendus nemo sequi aut ab, sunt porro esse. Iure, fugiat unde, magni accusantium pariatur blanditiis dolorum nostrum atque asperiores assumenda provident commodi. Amet saepe ea rem velit, distinctio maxime ad, sunt delectus ullam voluptates quia quibusdam vitae id facere eos qui praesentium accusantium autem dolores molestias sit. Id, ratione consectetur corrupti. Incidunt architecto, non velit voluptas minima quibusdam, distinctio labore cupiditate delectus earum, dicta eos, enim. Provident architecto ad, assumenda, mollitia consequatur inventore. Modi totam quas consequatur eveniet, eum culpa similique veritatis sint praesentium obcaecati nihil nam inventore.</p>
			<p>Fugit tenetur nesciunt fugiat, autem ad excepturi. Accusantium cumque, eveniet nostrum, minus at rem odit quia quam incidunt exercitationem voluptas amet, itaque ut, maiores quaerat? Culpa quaerat obcaecati quis, perferendis dolorem aperiam, pariatur, velit quae laboriosam fuga nulla doloremque odio laborum molestiae corporis eligendi. Ut ad dignissimos dolorum obcaecati blanditiis aliquam et numquam distinctio in excepturi, voluptatibus porro molestias, quo sequi libero at ipsum iusto ab suscipit necessitatibus unde omnis? Minus debitis dicta tempore nihil at fugit sapiente quam delectus ex ipsam reprehenderit eveniet, fuga, illo officiis! Corporis ex aliquid quod, voluptatibus ullam, non perspiciatis quibusdam similique reiciendis ad officia?</p>
			<p>Molestiae impedit beatae provident ipsum, veritatis, necessitatibus. Impedit tempora molestiae, magni. At, velit rem, recusandae repellendus quia impedit assumenda veritatis, explicabo aperiam autem porro, inventore vero nihil dolore voluptate cumque et commodi eaque aut molestias quidem. Illum sunt voluptates nemo impedit dolor ipsa repellendus minima quos et nesciunt totam iure maiores, cumque quia! In molestias asperiores dicta natus. Ad id minima sed nesciunt deleniti ducimus. Eaque autem error, quas earum accusantium laboriosam iure ipsam sapiente necessitatibus numquam, a aliquam, aliquid eveniet enim quod beatae! Quo doloribus, quaerat, quia asperiores quae ratione voluptatibus deleniti suscipit iure aliquid obcaecati in officia? Ab!</p>
			<p>Blanditiis ab delectus incidunt numquam ullam repellendus ipsum, dolore, non reprehenderit! Sapiente maxime quibusdam cumque laboriosam facilis harum, tempora, accusantium reprehenderit libero aspernatur autem atque consequatur reiciendis unde voluptas. Fugiat, perspiciatis eligendi! Quia ex nihil, rerum natus voluptate eos sequi itaque quidem blanditiis quasi laborum quae minima. Minima assumenda ut possimus quisquam quasi reprehenderit eveniet. Inventore dolor excepturi tenetur hic fuga rem possimus dolores deleniti nihil quos cum, fugit, ipsa nisi corrupti amet! A iusto nam consequuntur rem ullam soluta quo ea, aperiam est adipisci libero amet nulla voluptate! Iste veritatis facere, atque ab id dignissimos ad autem fugit hic!</p>
			<p>Fugit quis, praesentium nulla molestiae beatae quasi cum saepe libero magni at nisi eius, inventore hic, tenetur repudiandae ratione pariatur id a repellat. Pariatur earum a, voluptate exercitationem! Eligendi velit expedita, aspernatur consequatur itaque numquam iusto aperiam aut obcaecati alias accusamus deserunt quaerat atque dolorem ad blanditiis, error excepturi sapiente consequuntur porro, quisquam aliquid. Libero, nesciunt debitis voluptatum id voluptas ea eaque nemo laboriosam, quae accusantium quo! Cupiditate excepturi ratione quos optio vero eius molestias distinctio quasi nostrum delectus maxime, cum, sunt autem quam inventore, neque. Natus autem nulla minima ipsa quidem culpa necessitatibus eum, porro cum. Quaerat, velit, odio.</p>
			<p>Quae facilis, autem tempore sunt culpa fuga doloribus id, error repellendus reiciendis cupiditate eum cumque nam quos placeat totam nisi in assumenda officiis? Ipsa beatae quia, officia consequuntur odit voluptates ea laborum necessitatibus fugiat quo impedit hic possimus error aliquam autem nemo vitae similique quas assumenda id deserunt in eligendi eius. Rem labore tenetur, ipsum minima ullam alias quod consequuntur libero cumque quaerat inventore sit nam magni dolore saepe earum error obcaecati, veritatis ab mollitia. Accusamus ad nulla, quibusdam! Sapiente, tempore, sed consequuntur modi beatae consequatur maxime optio voluptatibus maiores mollitia, officiis exercitationem dolorem voluptatum cumque qui eveniet totam alias.</p>
			<p>At error, esse aspernatur harum dolorum perferendis vel officiis, expedita cumque, omnis et accusantium, aut officia quo! Reiciendis, quidem obcaecati quas alias voluptas commodi! Vitae eaque repellat, aperiam ab iusto! Fugiat, perspiciatis qui porro dolore quidem cum excepturi necessitatibus odit, voluptatem ex iusto accusantium! Ipsa molestias sed, alias saepe consectetur dolores suscipit cupiditate vitae facilis. Explicabo, eum labore repudiandae odit possimus natus similique laboriosam quisquam deleniti, minus quam. Sunt, nostrum perferendis, quisquam, repellat quibusdam ducimus aut voluptates autem aliquid iusto aperiam inventore iste. Dolores, atque perferendis, quidem laborum quas vel quia, vero at commodi exercitationem tempora blanditiis explicabo neque maxime.</p>
			<p>Iusto obcaecati cum eos illum optio mollitia ipsam inventore odio sequi quidem aliquam id rem deserunt eaque praesentium nihil dolorem laboriosam, harum soluta earum. Beatae et voluptatibus consectetur optio veritatis, culpa asperiores, in, molestiae assumenda animi, quo modi magni accusantium est magnam exercitationem repellat neque adipisci corporis! Aliquam voluptatum deleniti dignissimos, voluptas inventore assumenda aliquid maiores quidem enim. Ab eveniet ducimus, minima nam dignissimos aliquid, temporibus expedita id? Cupiditate perferendis aut, eius debitis vel exercitationem ex eum fuga error alias deserunt deleniti omnis possimus! Saepe quam adipisci a magni laboriosam ad beatae explicabo corporis eos, deleniti natus est ut sit.</p>
			<p>Commodi tempora quasi quidem nam beatae praesentium eveniet deleniti dolorum, facilis, similique, fugiat odio laudantium suscipit architecto veritatis vero in nobis nisi dolores quis accusantium? Delectus deleniti non odit, blanditiis aut necessitatibus, voluptatum fuga commodi doloribus dolore autem temporibus reprehenderit provident facere quisquam aspernatur eum magnam at repellat asperiores consectetur praesentium. Cupiditate sit porro quis, alias consequatur distinctio. Maiores voluptatibus magni dignissimos beatae in veritatis suscipit qui, ipsum quasi laborum, ducimus ab temporibus, necessitatibus enim, aperiam deserunt! Nostrum fugiat doloremque fuga rem voluptatum, obcaecati, aperiam necessitatibus aspernatur, accusantium quibusdam ipsa perspiciatis esse cupiditate corporis expedita asperiores at dolores ducimus tempore!</p>
			<p>Labore sed quisquam quibusdam inventore laboriosam, laborum natus, temporibus dignissimos veniam perferendis et voluptatem, amet dolorum. Accusantium minima voluptatum consectetur explicabo impedit dignissimos, illum inventore ab eveniet voluptatem. Voluptatem saepe, accusamus quo iste veniam aspernatur voluptatum voluptate quidem eum quas sint vitae cum, dolor debitis sapiente doloribus enim aut quae dolore rerum non, commodi deleniti id molestiae voluptates. Ipsam illo quae enim doloremque similique, deserunt culpa molestiae, dolores totam iusto laboriosam, aliquam suscipit deleniti odit quas. Sed magni quas accusamus totam illo cupiditate non voluptatem quasi eligendi quae ex culpa nesciunt, autem impedit porro accusantium esse, ipsam molestias doloremque ratione!</p>
			<p>Harum corrupti velit quod hic doloribus recusandae qui fuga animi placeat nesciunt tenetur, modi, dolorum sed, autem rerum dolorem! Delectus aut accusantium incidunt, itaque cum quibusdam obcaecati nisi officiis est aspernatur! Culpa dignissimos quam atque suscipit voluptatibus, perferendis delectus libero rem dolore voluptatum ratione soluta reprehenderit animi adipisci expedita quis eveniet ipsum molestiae molestias magnam sit ducimus eaque sed nesciunt. Cum adipisci dicta quam quo minus, ratione iste quibusdam dignissimos earum facere asperiores voluptatem, doloribus in eum quis! Laudantium, tempora, quibusdam? Nesciunt alias, magnam maxime, pariatur quasi et laborum ab accusamus, odio quaerat necessitatibus, fugiat possimus vel saepe odit quam!</p>
			<p>Repellendus iusto hic, maiores! Et minima vero dolorum, magnam delectus sint veritatis porro unde explicabo voluptate nam reiciendis illo, officiis neque nisi qui praesentium numquam. Quos odio exercitationem fuga nostrum, enim, hic repudiandae eius quia at nam velit quidem reiciendis ea perspiciatis accusantium dolores facilis dolorum asperiores architecto molestias explicabo, corrupti, est eos! Ducimus cumque fugiat similique pariatur, sunt, molestias quo! Officia culpa odio porro rem qui nobis? Eveniet nobis quia, ipsam. Minima est mollitia facere consequatur tempore, esse quis molestiae deleniti provident cum libero accusantium a neque, totam doloribus eius voluptatibus modi sunt dolor, at soluta? Ratione, totam vitae!</p>
			<p>Quidem consequuntur soluta id, iusto, asperiores iste accusamus. Natus sequi veniam autem aliquid dolor, mollitia perspiciatis recusandae placeat dolorem harum blanditiis, illum fuga, vero ab, iure impedit obcaecati voluptatem iste alias magni quia possimus laboriosam ipsam quo. Natus, soluta. Molestias, rem, aperiam perferendis officia nesciunt placeat, eligendi saepe, dolores voluptate quos commodi quae animi accusantium accusamus nostrum! Aliquam hic blanditiis est iusto esse. Omnis incidunt rem, cum quia quaerat iure in, minus consectetur fugit a quas vel odio consequatur eaque debitis quo ipsam hic assumenda. Voluptatem est, qui deleniti totam voluptates illum sit ratione quasi, molestias suscipit temporibus alias saepe.</p>
			<p>Perferendis fugit, soluta earum aliquid mollitia cum dolorem inventore, officiis est voluptates impedit aspernatur fugiat sint ullam aut porro ipsa minus repellat quaerat neque. Dolorum veritatis magni quod blanditiis temporibus voluptas, provident quasi, mollitia ducimus repellat minima eaque architecto pariatur alias! Architecto earum ad aspernatur voluptate vero, facilis officia eius ducimus iure ea magni fuga molestiae nemo, nisi reiciendis. Doloribus eaque quia dolore culpa corporis non hic facilis in et eum obcaecati, expedita consequatur, est perspiciatis vero possimus cupiditate tenetur similique blanditiis eligendi! Aspernatur maxime, veniam et at accusamus cumque sequi facere, quidem dolor, autem vitae ipsum aut magni inventore!</p>
			<p>Tempore vitae veritatis assumenda doloremque et, ipsam deleniti distinctio vero aperiam accusantium maxime autem sit ea rerum sunt voluptatum praesentium, porro! Quas architecto molestias ducimus sapiente illum sequi quibusdam nemo alias velit ratione. Libero temporibus, expedita nemo, consectetur veritatis possimus in ratione alias ducimus molestias debitis explicabo aliquam beatae placeat officia quos eius aspernatur officiis? Sunt porro est veniam saepe aspernatur dolores, inventore ullam officia tempora nemo necessitatibus, quasi quis, vel eum? Eveniet incidunt odio omnis, tempora in voluptates, minima voluptatum iste eligendi sed, libero esse ullam placeat blanditiis assumenda. Eaque ducimus iusto animi cumque eum non, voluptatum, explicabo similique.</p>
			<p>Quis est excepturi, voluptatibus molestiae, blanditiis vero eligendi natus dolorem officia rem ratione illum soluta deserunt eum! Blanditiis inventore dolorum quos beatae ullam, tempora ea esse quis dolor maxime dolores. Amet eaque, vel sed provident architecto deserunt praesentium nostrum, quasi quibusdam, ratione voluptatum mollitia odit maxime molestiae excepturi numquam enim sapiente tempore accusamus. Consequatur, facere nemo nesciunt ab voluptatem saepe quo, ea vel explicabo. Assumenda officia dolore doloribus delectus ratione, pariatur nisi ducimus! Dolorem accusamus, quisquam incidunt cumque. Aut pariatur ea ipsa hic rem nisi quod nihil molestiae dicta tempore aspernatur a debitis ad iste, nesciunt culpa! Cumque, perferendis, nisi?</p>
		</div>
	</section>

	<?php include 'templates/footer.php'; ?>
</body>
</html>